const { placeModel } = require('./places');
const { placeTypeModel } = require('./placeTypeModel');

async function insertExamplePlace() {
  try {
    const coffeeShopData = {
      place_name: "Stumptown Coffee Roasters",
      place_url: "/stumptown-coffee-roasters",
      price_range: "$$",
      phone: "+15031234567",
      website: "https://www.stumptowncoffee.com",
      latitude: 45.5231,
      longitude: -122.6765
      // created_at and updated_at will be auto-generated by DEFAULT NOW()
    };

    console.log('Inserting coffee shop data:', coffeeShopData);
    const newPlace = await placeModel.insert(coffeeShopData);
    console.log('Successfully inserted coffee shop:', newPlace);
    return newPlace;
  } catch (error) {
    console.error('Failed to insert coffee shop data:', error);
  }
}

// Execute the function if this script is run directly
if (require.main === module) {
  insertExamplePlace()
    .then(() => process.exit(0))
    .catch(err => {
      console.error(err);
      process.exit(1);
    });
}


async function insertExamplePlaceWithTypes() {
    try {
      // First, insert a place
      const coffeeShop = {
        place_name: "coffee shop test",
        place_url: "/abc",
        price_range: "$$",
        phone: "+123456789",
        website: "https://example.com",
        latitude: 45.6789,
        longitude: -123.4567
      };
  
      console.log('Inserting coffee shop...');
      const newPlace = await placeModel.insert(coffeeShop);
      console.log('Successfully inserted coffee shop:', newPlace);
      
      // Now insert types for this place
      const placeTypes = [
        { place_id: newPlace.place_id, type_name: "Coffee Shop" },
        { place_id: newPlace.place_id, type_name: "Roastery" }
      ];
  
      console.log('Inserting place types...');
      const insertedTypes = await placeTypeModel.insertMany(placeTypes);
      console.log('Successfully inserted place types:', insertedTypes);
      
      return { place: newPlace, types: insertedTypes };
    } catch (error) {
      console.error('Failed to insert place with types:', error);
    }
  }
  
  if (require.main === module) {
    insertExamplePlaceWithTypes()
      .then(() => process.exit(0))
      .catch(err => {
        console.error(err);
        process.exit(1);
      });
  }


module.exports = { insertExamplePlace };